# Generated by Django 5.2.10 on 2026-02-03 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_year', models.IntegerField(blank=True, null=True)),
                ('position_ran', models.CharField(blank=True, max_length=50, null=True)),
                ('was_incumbent', models.BooleanField(blank=True, null=True)),
                ('candidate_votes', models.IntegerField(blank=True, null=True)),
                ('registered_votes', models.IntegerField(blank=True, null=True)),
                ('voters_who_voted', models.IntegerField(blank=True, null=True)),
                ('turnout', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.URLField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('related_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_candidates', to='data_source.candidate')),
            ],
        ),
    ]
