# Generated by Django 5.2.10 on 2026-02-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
