# Generated by Django 5.2.10 on 2026-02-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0002_alter_candidate_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='family_group',
            field=models.TextField(blank=True, choices=[('chan', 'Chan'), ('radaza', 'Radaza')], null=True),
        ),
    ]
