# Generated by Django 5.2.10 on 2026-02-03 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0003_candidate_family_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateVoteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_year', models.IntegerField(blank=True, null=True)),
                ('position_ran', models.CharField(blank=True, max_length=50, null=True)),
                ('was_incumbent', models.BooleanField(blank=True, null=True)),
                ('candidate_votes', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_year', models.IntegerField(blank=True, null=True)),
                ('registered_votes', models.IntegerField(blank=True, null=True)),
                ('voters_who_voted', models.IntegerField(blank=True, null=True)),
                ('turnout', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='VoterData',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='family_group',
            field=models.TextField(blank=True, choices=[('chan', 'Chan'), ('radaza', 'Radaza'), ('caratao', 'Caratao')], null=True),
        ),
        migrations.AddField(
            model_name='candidatevotedata',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data', to='data_source.candidate'),
        ),
    ]
