# Generated by Django 5.2.10 on 2026-02-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0004_candidatevotedata_electionresult_delete_voterdata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatePerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_year', models.IntegerField(blank=True, null=True)),
                ('esi', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('rsi', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('normalized_vs', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='candidatevotedata',
            name='total_votes_for_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electionresult',
            name='turnout_volatilitu',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='candiate-profile/'),
        ),
    ]
