# Generated by Django 5.2.10 on 2026-02-04 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0005_candidateperformancemetrics_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electionresult',
            old_name='turnout_volatilitu',
            new_name='turnout_volatility',
        ),
    ]
