# Generated by Django 5.2.10 on 2026-02-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0006_rename_turnout_volatilitu_electionresult_turnout_volatility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateperformancemetrics',
            name='esi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='candidateperformancemetrics',
            name='rsi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='electionresult',
            name='turnout',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='electionresult',
            name='turnout_volatility',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
