# Generated by Django 5.2.10 on 2026-02-04 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0007_alter_candidateperformancemetrics_esi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electionresult',
            old_name='registered_votes',
            new_name='registered_voters',
        ),
    ]
