# Generated by Django 5.2.10 on 2026-02-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0008_rename_registered_votes_electionresult_registered_voters'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CandidatePerformanceMetrics',
        ),
        migrations.AddField(
            model_name='candidatevotedata',
            name='esi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='candidatevotedata',
            name='normalized_vs',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='candidatevotedata',
            name='rsi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
