# Generated by Django 5.2.10 on 2026-02-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0009_delete_candidateperformancemetrics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionresult',
            name='taf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
