# Generated by Django 5.2.10 on 2026-02-06 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0010_electionresult_taf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatevotedata',
            old_name='rsi',
            new_name='rpi',
        ),
    ]
