# Generated by Django 5.2.10 on 2026-02-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0011_rename_rsi_candidatevotedata_rpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatevotedata',
            name='is_winner',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
