# Generated by Django 5.2.10 on 2026-02-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0012_candidatevotedata_is_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatevotedata',
            name='position_ran',
            field=models.TextField(blank=True, choices=[('mayor', 'Mayor'), ('congressan', 'Congressman')], null=True),
        ),
    ]
