# Generated by Django 5.2.10 on 2026-02-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0013_alter_candidatevotedata_position_ran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatevotedata',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
    ]
