# Generated by Django 5.2.10 on 2026-02-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0015_alter_candidatevotedata_position_ran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatevotedata',
            name='was_incumbent',
            field=models.BooleanField(default=False),
        ),
    ]
