# Generated by Django 5.2.10 on 2026-02-13 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0017_candidate_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='related_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_candidates', to='data_source.candidate'),
        ),
    ]
