# Generated by Django 5.2.10 on 2026-02-19 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0018_alter_candidate_related_candidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInishgts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_inisights', to='data_source.candidate')),
            ],
        ),
    ]
