# Generated by Django 5.2.10 on 2026-02-19 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0019_aiinishgts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AIInishgts',
            new_name='AIInsights',
        ),
    ]
