# Generated by Django 5.2.10 on 2026-02-19 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0020_rename_aiinishgts_aiinsights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiinsights',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_insights', to='data_source.candidate'),
        ),
        migrations.CreateModel(
            name='CandidateAchievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achiements', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achievements', to='data_source.candidate')),
            ],
        ),
    ]
