# Generated by Django 5.2.10 on 2026-02-19 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0021_alter_aiinsights_candidate_candidateachievements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateachievements',
            old_name='achiements',
            new_name='achievement',
        ),
    ]
