# Generated by Django 5.2.10 on 2026-02-23 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0022_rename_achiements_candidateachievements_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatevotedata',
            name='position_ran',
            field=models.TextField(blank=True, choices=[('mayor', 'Mayor'), ('congressman', 'Congressman'), ('vice mayor', 'Vice Mayor')], null=True),
        ),
        migrations.CreateModel(
            name='ESIForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_year', models.IntegerField(blank=True, null=True)),
                ('predicted_value', models.TextField(blank=True, null=True)),
                ('lower_bound', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('upper_bound', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('model', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='esi_forecast', to='data_source.candidate')),
            ],
        ),
    ]
