# Generated by Django 5.2.10 on 2026-02-24 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0023_alter_candidatevotedata_position_ran_esiforecast'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateSocialMediaActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_activity', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='social_media_activity', to='data_source.candidate')),
            ],
        ),
    ]
