# Generated by Django 5.2.10 on 2026-02-24 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0024_candidatesocialmediaactivity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatesocialmediaactivity',
            old_name='social_activity',
            new_name='social_media_activity',
        ),
    ]
